a = input()
b = input()
c = input()
aa = a.lower()
bb = b.lower()
cc = c.lower()
print(aa,bb,cc)
aa = a.upper()
bb = b.upper()
cc = c.upper()
print(aa,bb,cc)
aa = a.capitalize()
bb = b.capitalize()
cc = c.capitalize()
print(aa,bb,cc)
print("Количество",aa,"=")
a_num = int(input())
print("Количество",bb,"=")
b_num = int(input())
print("Количество",cc,"=")
c_num = int(input())
print("На данный момент у нас на складе: {0} - {1}; {2} - {3}; {4} - {5}.".format(aa,a_num,bb,b_num,cc,c_num))